// Autogenerated seedData.js with local coverImage paths
const categories = [
  {
    "name": "Programming",
    "description": "Software engineering, languages, and coding practices."
  },
  {
    "name": "Artificial Intelligence",
    "description": "Neural networks, machine learning, and future technology."
  },
  {
    "name": "Machine Learning",
    "description": "Algorithms, training models, and statistics."
  },
  {
    "name": "Data Science",
    "description": "Big data, analysis, visualization, and Python."
  },
  {
    "name": "Fantasy",
    "description": "Magic, mythical worlds, and epic adventures."
  },
  {
    "name": "Romance",
    "description": "Love stories and emotional journeys."
  },
  {
    "name": "Mystery",
    "description": "Suspense, investigators, and unsolved crimes."
  },
  {
    "name": "Thriller",
    "description": "Fast-paced, action-packed suspense."
  },
  {
    "name": "Science Fiction",
    "description": "Space exploration, time travel, and futuristic tech."
  },
  {
    "name": "Horror",
    "description": "Spooky tales, monsters, and psychological terror."
  },
  {
    "name": "Biography",
    "description": "Life stories of notable individuals."
  },
  {
    "name": "Business",
    "description": "Economics, finance, and entrepreneurship."
  },
  {
    "name": "Self-Help",
    "description": "Personal development, productivity, and motivation."
  },
  {
    "name": "Children's Books",
    "description": "Bedtime stories and early learning."
  },
  {
    "name": "Comics",
    "description": "Graphic novels and illustrated stories."
  },
  {
    "name": "Academic",
    "description": "Textbooks and educational literature."
  },
  {
    "name": "Engineering",
    "description": "Core principles of civil, electrical, and mechanical engineering."
  },
  {
    "name": "Competitive Exams",
    "description": "Study guides for GATE, JEE, UPSC, etc."
  },
  {
    "name": "Poetry",
    "description": "Verses, expressions, and creative writing."
  },
  {
    "name": "Religion",
    "description": "Faith, spirituality, and religious history."
  },
  {
    "name": "Health",
    "description": "Fitness, nutrition, and mental health."
  },
  {
    "name": "Cooking",
    "description": "Recipes, culinary skills, and cuisines."
  },
  {
    "name": "History",
    "description": "Global historical events, eras, and empires."
  },
  {
    "name": "Travel",
    "description": "Guides, journals, and exploration."
  },
  {
    "name": "Technology",
    "description": "General computer science, hardware, and gadgets."
  }
];

const books = [
  {
    "title": "Clean Code: A Handbook of Agile Software Craftsmanship",
    "author": "Robert C. Martin",
    "categoryName": "Programming",
    "description": "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn't have to be that way.",
    "publisher": "Prentice Hall",
    "language": "English",
    "isbn": "9780132350884",
    "pageCount": 464,
    "price": 699,
    "originalPrice": 899,
    "stock": 15,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "clean code",
      "programming",
      "agile",
      "robert martin"
    ],
    "coverImage": "/images/books/clean-code-a-handbook-of-agile-software-craftsmanship.jpg"
  },
  {
    "title": "JavaScript: The Good Parts",
    "author": "Douglas Crockford",
    "categoryName": "Programming",
    "description": "Most programming languages contain good and bad parts, but JavaScript has more than its share of the bad, having been developed and released in a hurry before it could be refined.",
    "publisher": "O'Reilly Media",
    "language": "English",
    "isbn": "9780596517748",
    "pageCount": 172,
    "price": 499,
    "originalPrice": 599,
    "stock": 8,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "javascript",
      "web programming",
      "crockford"
    ],
    "coverImage": "/images/books/javascript-the-good-parts.jpg"
  },
  {
    "title": "Pragmatic Programmer, The: Your Journey to Mastery",
    "author": "David Thomas",
    "categoryName": "Programming",
    "description": "The Pragmatic Programmer cuts through the increasing specialization and technicalities of modern software development to examine the core process--taking a requirement and producing working, maintainable code.",
    "publisher": "Addison-Wesley Professional",
    "language": "English",
    "isbn": "9780135957059",
    "pageCount": 352,
    "price": 799,
    "originalPrice": 999,
    "stock": 12,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "programming",
      "pragmatic",
      "development"
    ],
    "coverImage": "/images/books/pragmatic-programmer-the-your-journey-to-mastery.jpg"
  },
  {
    "title": "Artificial Intelligence: A Modern Approach",
    "author": "Stuart Russell",
    "categoryName": "Artificial Intelligence",
    "description": "The most comprehensive, up-to-date introduction to the theory and practice of artificial intelligence. Ideal for undergraduate or graduate-level courses in Artificial Intelligence.",
    "publisher": "Pearson",
    "language": "English",
    "isbn": "9780134610993",
    "pageCount": 1152,
    "price": 1299,
    "originalPrice": 1599,
    "stock": 5,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "ai",
      "artificial intelligence",
      "russell",
      "norvig"
    ],
    "coverImage": "/images/books/artificial-intelligence-a-modern-approach.jpg"
  },
  {
    "title": "Introduction to Machine Learning with Python",
    "author": "Andreas C. Müller",
    "categoryName": "Machine Learning",
    "description": "Machine learning has become an integral part of many commercial and research applications, but this field is not exclusive to large companies with extensive research teams. If you use Python, even as a beginner, this book will teach you practical ways to build your own machine learning solutions.",
    "publisher": "O'Reilly Media",
    "language": "English",
    "isbn": "9781449369415",
    "pageCount": 392,
    "price": 899,
    "originalPrice": 1199,
    "stock": 0,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "machine learning",
      "python",
      "scikit-learn",
      "ml"
    ],
    "coverImage": "/images/books/introduction-to-machine-learning-with-python.jpg"
  },
  {
    "title": "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow",
    "author": "Aurélien Géron",
    "categoryName": "Machine Learning",
    "description": "Through a series of recent breakthroughs, deep learning has boosted the entire field of machine learning. Now, even programmers who know close to nothing about this technology can use simple, efficient tools to implement programs capable of learning from data.",
    "publisher": "O'Reilly Media",
    "language": "English",
    "isbn": "9781492032649",
    "pageCount": 856,
    "price": 1199,
    "originalPrice": 1499,
    "stock": 10,
    "isFeatured": true,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "machine learning",
      "tensorflow",
      "keras",
      "deep learning"
    ],
    "coverImage": "/images/books/hands-on-machine-learning-with-scikit-learn-keras-and-tensorflow.jpg"
  },
  {
    "title": "Python for Data Analysis",
    "author": "Wes McKinney",
    "categoryName": "Data Science",
    "description": "Get complete instructions for manipulating, processing, cleaning, and crunching datasets in Python. Updated for Python 3.6, the second edition of this hands-on guide is packed with practical case studies.",
    "publisher": "O'Reilly Media",
    "language": "English",
    "isbn": "9781491957660",
    "pageCount": 544,
    "price": 799,
    "originalPrice": 999,
    "stock": 14,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "data science",
      "pandas",
      "numpy",
      "python"
    ],
    "coverImage": "/images/books/python-for-data-analysis.jpg"
  },
  {
    "title": "Deep Learning",
    "author": "Ian Goodfellow",
    "categoryName": "Artificial Intelligence",
    "description": "An introduction to a broad range of topics in deep learning, covering mathematical and conceptual background, deep learning techniques used in industry, and research perspectives.",
    "publisher": "MIT Press",
    "language": "English",
    "isbn": "9780262035613",
    "pageCount": 800,
    "price": 1499,
    "originalPrice": 1799,
    "stock": 6,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "deep learning",
      "neural networks",
      "goodfellow"
    ],
    "coverImage": "/images/books/deep-learning.jpg"
  },
  {
    "title": "The Hobbit",
    "author": "J.R.R. Tolkien",
    "categoryName": "Fantasy",
    "description": "A glorious illustrated edition of Tolkien's masterpiece. Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely travelling any farther than the pantry of his hobbit-hole in Bag End. But his contentment is disturbed when the wizard Gandalf and a company of thirteen dwarfs arrive on his doorstep.",
    "publisher": "HarperCollins",
    "language": "English",
    "isbn": "9780007270613",
    "pageCount": 310,
    "price": 399,
    "originalPrice": 499,
    "stock": 20,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "hobbit",
      "tolkien",
      "fantasy",
      "adventure"
    ],
    "coverImage": "/images/books/the-hobbit.jpg"
  },
  {
    "title": "Harry Potter and the Sorcerer's Stone",
    "author": "J.K. Rowling",
    "categoryName": "Fantasy",
    "description": "Harry Potter has no idea how famous he is. That's because he's being raised by his miserable aunt and uncle who are terrified Harry will learn that he's a wizard, just as his parents were. But everything changes when Harry is summoned to attend an infamous school for wizards...",
    "publisher": "Scholastic",
    "language": "English",
    "isbn": "9780590353427",
    "pageCount": 309,
    "price": 349,
    "originalPrice": 450,
    "stock": 25,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "harry potter",
      "rowling",
      "magic",
      "hogwarts"
    ],
    "coverImage": "/images/books/harry-potter-and-the-sorcerers-stone.jpg"
  },
  {
    "title": "Pride and Prejudice",
    "author": "Jane Austen",
    "categoryName": "Romance",
    "description": "Pride and Prejudice is an 1813 romantic novel of manners written by Jane Austen. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book who learns about the repercussions of hasty judgments.",
    "publisher": "T. Egerton",
    "language": "English",
    "isbn": "9780141439518",
    "pageCount": 432,
    "price": 199,
    "originalPrice": 250,
    "stock": 15,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "classic",
      "romance",
      "jane austen"
    ],
    "coverImage": "/images/books/pride-and-prejudice.jpg"
  },
  {
    "title": "It Ends with Us",
    "author": "Colleen Hoover",
    "categoryName": "Romance",
    "description": "Lily hasn't always had it easy, but that's never stopped her from working hard for the life she wants. She's come a long way from the small town in Maine where she grew up—she graduated from college, moved to Boston, and started her own business.",
    "publisher": "Atria Books",
    "language": "English",
    "isbn": "9781501110368",
    "pageCount": 384,
    "price": 299,
    "originalPrice": 399,
    "stock": 18,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "romance",
      "colleen hoover",
      "drama"
    ],
    "coverImage": "/images/books/it-ends-with-us.jpg"
  },
  {
    "title": "Dune",
    "author": "Frank Herbert",
    "categoryName": "Science Fiction",
    "description": "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the \"spice\" melange, a drug capable of extending life and enhancing consciousness.",
    "publisher": "Chilton Books",
    "language": "English",
    "isbn": "9780441172719",
    "pageCount": 604,
    "price": 499,
    "originalPrice": 599,
    "stock": 9,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "dune",
      "sci-fi",
      "space opera",
      "herbert"
    ],
    "coverImage": "/images/books/dune.jpg"
  },
  {
    "title": "Project Hail Mary",
    "author": "Andy Weir",
    "categoryName": "Science Fiction",
    "description": "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn't know that. He can't even remember his own name, let alone the nature of his assignment.",
    "publisher": "Ballantine Books",
    "language": "English",
    "isbn": "9780593135204",
    "pageCount": 476,
    "price": 450,
    "originalPrice": 550,
    "stock": 10,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "sci-fi",
      "andy weir",
      "space"
    ],
    "coverImage": "/images/books/project-hail-mary.jpg"
  },
  {
    "title": "The Shining",
    "author": "Stephen King",
    "categoryName": "Horror",
    "description": "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to reconnect with his family and work on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote... and more sinister.",
    "publisher": "Doubleday",
    "language": "English",
    "isbn": "9780385121682",
    "pageCount": 447,
    "price": 349,
    "originalPrice": 450,
    "stock": 8,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "horror",
      "stephen king",
      "classic"
    ],
    "coverImage": "/images/books/the-shining.jpg"
  },
  {
    "title": "Dracula",
    "author": "Bram Stoker",
    "categoryName": "Horror",
    "description": "During a business visit to Count Dracula's castle in Transylvania, a young English solicitor finds himself at the center of a series of horrifying incidents. Stoker's gothic masterpiece introduced the world to the legendary vampire Count Dracula.",
    "publisher": "Archibald Constable & Co.",
    "language": "English",
    "isbn": "9780141439846",
    "pageCount": 418,
    "price": 249,
    "originalPrice": 299,
    "stock": 12,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "horror",
      "dracula",
      "gothic"
    ],
    "coverImage": "/images/books/dracula.jpg"
  },
  {
    "title": "And Then There Were None",
    "author": "Agatha Christie",
    "categoryName": "Mystery",
    "description": "Ten strangers, apparently with little in common, are lured to a solitary island mansion off the coast of Devon by the mysterious U.N. Owen. Over dinner, a recorded message accuses each of them of having a guilty secret, and by the end of the night, one of them is dead.",
    "publisher": "Collins Crime Club",
    "language": "English",
    "isbn": "9780007136834",
    "pageCount": 272,
    "price": 299,
    "originalPrice": 399,
    "stock": 14,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "mystery",
      "agatha christie",
      "classic"
    ],
    "coverImage": "/images/books/and-then-there-were-none.jpg"
  },
  {
    "title": "The Da Vinci Code",
    "author": "Dan Brown",
    "categoryName": "Thriller",
    "description": "While in Paris on business, Harvard symbologist Robert Langdon receives an urgent late-night phone call: the elderly curator of the Louvre has been murdered inside the museum. Near the body, police have found a baffling cipher.",
    "publisher": "Doubleday",
    "language": "English",
    "isbn": "9780385504201",
    "pageCount": 489,
    "price": 399,
    "originalPrice": 499,
    "stock": 0,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "thriller",
      "dan brown",
      "mystery"
    ],
    "coverImage": "/images/books/the-da-vinci-code.jpg"
  },
  {
    "title": "Gone Girl",
    "author": "Gillian Flynn",
    "categoryName": "Mystery",
    "description": "On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne's fifth wedding anniversary. Presents are being wrapped and reservations are being made when Nick's clever and beautiful wife disappears from their rented McMansion.",
    "publisher": "Crown Publishing Group",
    "language": "English",
    "isbn": "9780307588371",
    "pageCount": 419,
    "price": 349,
    "originalPrice": 450,
    "stock": 10,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "mystery",
      "thriller",
      "gillian flynn"
    ],
    "coverImage": "/images/books/gone-girl.jpg"
  },
  {
    "title": "The Silent Patient",
    "author": "Alex Michaelides",
    "categoryName": "Thriller",
    "description": "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with large windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
    "publisher": "Celadon Books",
    "language": "English",
    "isbn": "9781250301697",
    "pageCount": 336,
    "price": 329,
    "originalPrice": 399,
    "stock": 15,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "thriller",
      "suspense",
      "alex michaelides"
    ],
    "coverImage": "/images/books/the-silent-patient.jpg"
  },
  {
    "title": "Steve Jobs",
    "author": "Walter Isaacson",
    "categoryName": "Biography",
    "description": "Based on more than forty interviews with Jobs conducted over two years—as well as interviews with more than a hundred family members, friends, adversaries, competitors, and colleagues—Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur.",
    "publisher": "Simon & Schuster",
    "language": "English",
    "isbn": "9781451648539",
    "pageCount": 656,
    "price": 599,
    "originalPrice": 799,
    "stock": 11,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "biography",
      "steve jobs",
      "apple",
      "walter isaacson"
    ],
    "coverImage": "/images/books/steve-jobs.jpg"
  },
  {
    "title": "The Diary of a Young Girl",
    "author": "Anne Frank",
    "categoryName": "Biography",
    "description": "Discovered in the attic in which she spent the last years of her life, Anne Frank's remarkable diary has since become a world classic—a powerful reminder of the horrors of war and an eloquent testament to the human spirit.",
    "publisher": "Contact Publishing",
    "language": "English",
    "isbn": "9780553296983",
    "pageCount": 283,
    "price": 199,
    "originalPrice": 250,
    "stock": 20,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "biography",
      "anne frank",
      "holocaust"
    ],
    "coverImage": "/images/books/the-diary-of-a-young-girl.jpg"
  },
  {
    "title": "The Intelligent Investor",
    "author": "Benjamin Graham",
    "categoryName": "Business",
    "description": "The greatest investment advisor of the twentieth century, Benjamin Graham, taught and inspired people worldwide. Graham's philosophy of \"value investing\" -- which shields investors from substantial error and teaches them to develop long-term strategies -- has made The Intelligent Investor the stock market bible.",
    "publisher": "Harper Business",
    "language": "English",
    "isbn": "9780060555665",
    "pageCount": 640,
    "price": 649,
    "originalPrice": 799,
    "stock": 15,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "business",
      "finance",
      "investing",
      "graham"
    ],
    "coverImage": "/images/books/the-intelligent-investor.jpg"
  },
  {
    "title": "Zero to One: Notes on Startups, or How to Build the Future",
    "author": "Peter Thiel",
    "categoryName": "Business",
    "description": "If you want to build a better future, you must believe in secrets. The great secret of our time is that there are still uncharted frontiers to explore and new inventions to create. In Zero to One, legendary entrepreneur and investor Peter Thiel shows how we can find singular ways to create those new things.",
    "publisher": "Crown Business",
    "language": "English",
    "isbn": "9780804139298",
    "pageCount": 224,
    "price": 399,
    "originalPrice": 499,
    "stock": 18,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "business",
      "startups",
      "entrepreneurship",
      "thiel"
    ],
    "coverImage": "/images/books/zero-to-one-notes-on-startups-or-how-to-build-the-future.jpg"
  },
  {
    "title": "Rich Dad Poor Dad",
    "author": "Robert T. Kiyosaki",
    "categoryName": "Business",
    "description": "Rich Dad Poor Dad is Robert's story of growing up with two dads — his real father and the father of his best friend, his rich dad — and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich.",
    "publisher": "Warner Books",
    "language": "English",
    "isbn": "9781612680194",
    "pageCount": 336,
    "price": 349,
    "originalPrice": 450,
    "stock": 30,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "finance",
      "wealth",
      "kiyosaki"
    ],
    "coverImage": "/images/books/rich-dad-poor-dad.jpg"
  },
  {
    "title": "Wings of Fire",
    "author": "A.P.J. Abdul Kalam",
    "categoryName": "Biography",
    "description": "An autobiography of Dr. APJ Abdul Kalam, former President of India. It covers his early life and his work in Indian space research and missile programs.",
    "publisher": "Universities Press",
    "language": "English",
    "isbn": "9788173711466",
    "pageCount": 180,
    "price": 299,
    "originalPrice": 350,
    "stock": 22,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "biography",
      "kalam",
      "wings of fire",
      "india"
    ],
    "coverImage": "/images/books/wings-of-fire.jpg"
  },
  {
    "title": "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    "author": "James Clear",
    "categoryName": "Self-Help",
    "description": "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    "publisher": "Avery",
    "language": "English",
    "isbn": "9780735211292",
    "pageCount": 320,
    "price": 499,
    "originalPrice": 650,
    "stock": 40,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "self-help",
      "habits",
      "productivity",
      "james clear"
    ],
    "coverImage": "/images/books/atomic-habits-an-easy-proven-way-to-build-good-habits-break-bad-ones.jpg"
  },
  {
    "title": "The Power of Your Subconscious Mind",
    "author": "Joseph Murphy",
    "categoryName": "Self-Help",
    "description": "In The Power of Your Subconscious Mind, Dr. Joseph Murphy combines spiritual wisdom and scientific research to explain how the subconscious mind influences every aspect of our lives.",
    "publisher": "Prentice Hall",
    "language": "English",
    "isbn": "9781604590920",
    "pageCount": 200,
    "price": 199,
    "originalPrice": 299,
    "stock": 25,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "self-help",
      "subconscious",
      "mindset"
    ],
    "coverImage": "/images/books/the-power-of-your-subconscious-mind.jpg"
  },
  {
    "title": "How to Win Friends and Influence People",
    "author": "Dale Carnegie",
    "categoryName": "Self-Help",
    "description": "You can go after the job you want...and get it! You can take the job you have...and promote it! You can take any situation you're in...and make it work for you!",
    "publisher": "Simon & Schuster",
    "language": "English",
    "isbn": "9780671723651",
    "pageCount": 291,
    "price": 249,
    "originalPrice": 350,
    "stock": 18,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "self-help",
      "communication",
      "carnegie"
    ],
    "coverImage": "/images/books/how-to-win-friends-and-influence-people.jpg"
  },
  {
    "title": "The Subtle Art of Not Giving a F*ck",
    "author": "Mark Manson",
    "categoryName": "Self-Help",
    "description": "In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be \"positive\" all the time so that we can truly become better, happier people.",
    "publisher": "HarperOne",
    "language": "English",
    "isbn": "9780062457714",
    "pageCount": 224,
    "price": 399,
    "originalPrice": 499,
    "stock": 15,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "self-help",
      "mark manson",
      "mindset"
    ],
    "coverImage": "/images/books/the-subtle-art-of-not-giving-a-fck.jpg"
  },
  {
    "title": "Salt, Fat, Acid, Heat: Mastering the Elements of Good Cooking",
    "author": "Samin Nosrat",
    "categoryName": "Cooking",
    "description": "A visionary new master class in cooking that distills decades of professional experience into just four simple elements, from the woman declared \"America's next great cooking teacher\" by Alice Waters.",
    "publisher": "Simon & Schuster",
    "language": "English",
    "isbn": "9781476753836",
    "pageCount": 480,
    "price": 799,
    "originalPrice": 999,
    "stock": 8,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "cooking",
      "recipes",
      "culinary"
    ],
    "coverImage": "/images/books/salt-fat-acid-heat-mastering-the-elements-of-good-cooking.jpg"
  },
  {
    "title": "The Fitness Mindset",
    "author": "Brian Keane",
    "categoryName": "Health",
    "description": "How to get the body you want, keep the energy you need and still live the life you want. Brian Keane shows how to align your nutrition, exercise, and mindset for sustainable health.",
    "publisher": "Brian Keane Fitness",
    "language": "English",
    "isbn": "9781781332528",
    "pageCount": 258,
    "price": 299,
    "originalPrice": 399,
    "stock": 10,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "health",
      "fitness",
      "diet"
    ],
    "coverImage": "/images/books/the-fitness-mindset.jpg"
  },
  {
    "title": "The Very Hungry Caterpillar",
    "author": "Eric Carle",
    "categoryName": "Children's Books",
    "description": "The all-time classic picture book, from generation to generation, sold somewhere in the world every 30 seconds! Have you shared it with a child or grandchild in your life?",
    "publisher": "Philomel Books",
    "language": "English",
    "isbn": "9780399226908",
    "pageCount": 26,
    "price": 249,
    "originalPrice": 299,
    "stock": 35,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "children",
      "picture book",
      "classic"
    ],
    "coverImage": "/images/books/the-very-hungry-caterpillar.jpg"
  },
  {
    "title": "Watchmen",
    "author": "Alan Moore",
    "categoryName": "Comics",
    "description": "This Hugo Award-winning graphic novel chronicles the fall from grace of a group of super-heroes plagued by all-too-human failings. Along the way, the concept of the super-hero is dissected as the heroes are faced with a personal, ethical, and global crisis.",
    "publisher": "DC Comics",
    "language": "English",
    "isbn": "9780930289232",
    "pageCount": 416,
    "price": 699,
    "originalPrice": 899,
    "stock": 12,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "comics",
      "graphic novel",
      "watchmen",
      "dc"
    ],
    "coverImage": "/images/books/watchmen.jpg"
  },
  {
    "title": "Batman: The Killing Joke",
    "author": "Alan Moore",
    "categoryName": "Comics",
    "description": "Batman: The Killing Joke is a 1988 DC Comics graphic novel featuring the characters Batman and the Joker, written by Alan Moore and illustrated by Brian Bolland.",
    "publisher": "DC Comics",
    "language": "English",
    "isbn": "9781401216672",
    "pageCount": 64,
    "price": 399,
    "originalPrice": 499,
    "stock": 15,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "comics",
      "batman",
      "joker",
      "dc"
    ],
    "coverImage": "/images/books/batman-the-killing-joke.jpg"
  },
  {
    "title": "Charlotte's Web",
    "author": "E.B. White",
    "categoryName": "Children's Books",
    "description": "Some Pig. Humble. Radiant. These are the words in Charlotte's Web, high up in Zuckerman's barn. Charlotte's spiderweb tells of her feelings for a little pig named Wilbur, who simply wants a friend.",
    "publisher": "Harper & Brothers",
    "language": "English",
    "isbn": "9780061120060",
    "pageCount": 184,
    "price": 199,
    "originalPrice": 250,
    "stock": 20,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "children",
      "fiction",
      "animals"
    ],
    "coverImage": "/images/books/charlottes-web.jpg"
  },
  {
    "title": "Introduction to Algorithms",
    "author": "Thomas H. Cormen",
    "categoryName": "Academic",
    "description": "Some books on algorithms are rigorous but incomplete; others cover masses of material but lack rigor. Introduction to Algorithms uniquely combines rigor and comprehensiveness. The book covers a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers.",
    "publisher": "MIT Press",
    "language": "English",
    "isbn": "9780262033848",
    "pageCount": 1292,
    "price": 999,
    "originalPrice": 1299,
    "stock": 15,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "algorithms",
      "dsa",
      "academic",
      "cormen"
    ],
    "coverImage": "/images/books/introduction-to-algorithms.jpg"
  },
  {
    "title": "Software Engineering: A Practitioner's Approach",
    "author": "Roger S. Pressman",
    "categoryName": "Engineering",
    "description": "For almost three decades, Software Engineering: A Practitioner's Approach has been the world's leading guide to software engineering. The new edition represents a major restructuring and update of previous editions, solidifying the book's position as the most comprehensive guide to this important subject.",
    "publisher": "McGraw-Hill Education",
    "language": "English",
    "isbn": "9780078022128",
    "pageCount": 976,
    "price": 899,
    "originalPrice": 1099,
    "stock": 10,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "engineering",
      "software engineering",
      "pressman",
      "academic"
    ],
    "coverImage": "/images/books/software-engineering-a-practitioners-approach.jpg"
  },
  {
    "title": "GATE Computer Science and Information Technology",
    "author": "Trishna Knowledge Systems",
    "categoryName": "Competitive Exams",
    "description": "This book has been prepared by a team of highly experienced professionals and is geared to meet the requirements of students preparing for GATE. It covers core CS topics like DBMS, OS, TOC, and Compilers in a structured format.",
    "publisher": "Pearson Education",
    "language": "English",
    "isbn": "9789332575400",
    "pageCount": 1100,
    "price": 799,
    "originalPrice": 999,
    "stock": 5,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "gate",
      "competitive exams",
      "computer science"
    ],
    "coverImage": "/images/books/gate-computer-science-and-information-technology.jpg"
  },
  {
    "title": "UPSC Civil Services General Studies Paper I",
    "author": "MHE Experts",
    "categoryName": "Competitive Exams",
    "description": "A comprehensive guide for UPSC aspirants covering History, Geography, Indian Polity, Economy, Environment, and General Science.",
    "publisher": "McGraw-Hill",
    "language": "English",
    "isbn": "9789389811346",
    "pageCount": 1500,
    "price": 1199,
    "originalPrice": 1499,
    "stock": 8,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "upsc",
      "civil services",
      "general studies"
    ],
    "coverImage": "/images/books/upsc-civil-services-general-studies-paper-i.jpg"
  },
  {
    "title": "Concepts of Physics (Vol 1)",
    "author": "H.C. Verma",
    "categoryName": "Academic",
    "description": "Concepts of Physics is a very popular textbook for high school and intermediate students preparing for engineering entrance examinations. It explains physics principles clearly with mathematical derivations and practical problems.",
    "publisher": "Bharti Bhawan",
    "language": "English",
    "isbn": "9788177091878",
    "pageCount": 462,
    "price": 399,
    "originalPrice": 450,
    "stock": 25,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "physics",
      "hc verma",
      "jee",
      "academic"
    ],
    "coverImage": "/images/books/concepts-of-physics-vol-1.jpg"
  },
  {
    "title": "Higher Engineering Mathematics",
    "author": "B.S. Grewal",
    "categoryName": "Engineering",
    "description": "This book is a comprehensive guide for engineering students covering calculus, linear algebra, differential equations, and complex analysis. It contains solved examples and exercises.",
    "publisher": "Khanna Publishers",
    "language": "English",
    "isbn": "9788193328491",
    "pageCount": 1318,
    "price": 749,
    "originalPrice": 850,
    "stock": 12,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "engineering",
      "maths",
      "academic",
      "grewal"
    ],
    "coverImage": "/images/books/higher-engineering-mathematics.jpg"
  },
  {
    "title": "A Modern Approach to Verbal & Non-Verbal Reasoning",
    "author": "R.S. Aggarwal",
    "categoryName": "Competitive Exams",
    "description": "The book is very useful for various competitive examinations like Bank PO, SBI-PO, IBPS, RBI, MBA, MAT, CAT, UPSC, and SSC.",
    "publisher": "S. Chand Publishing",
    "language": "English",
    "isbn": "9789352535323",
    "pageCount": 1200,
    "price": 649,
    "originalPrice": 799,
    "stock": 18,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "reasoning",
      "rs aggarwal",
      "competitive exams"
    ],
    "coverImage": "/images/books/a-modern-approach-to-verbal-non-verbal-reasoning.jpg"
  },
  {
    "title": "Database System Concepts",
    "author": "Abraham Silberschatz",
    "categoryName": "Engineering",
    "description": "Presents the fundamental concepts of database management in an intuitive manner, allowing students to design, query, and use databases efficiently.",
    "publisher": "McGraw-Hill",
    "language": "English",
    "isbn": "9780073523323",
    "pageCount": 1376,
    "price": 849,
    "originalPrice": 1099,
    "stock": 0,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "database",
      "dbms",
      "engineering",
      "academic"
    ],
    "coverImage": "/images/books/database-system-concepts.jpg"
  },
  {
    "title": "Selected Poems",
    "author": "Gulzar",
    "categoryName": "Poetry",
    "description": "A bilingual collection of poetry by the legendary Gulzar, showcasing his range, depth, and lyrical beauty in Urdu/Hindi and English translation.",
    "publisher": "Penguin India",
    "language": "Hindi/English",
    "isbn": "9780143414216",
    "pageCount": 200,
    "price": 249,
    "originalPrice": 299,
    "stock": 15,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "poetry",
      "gulzar",
      "literature"
    ],
    "coverImage": "/images/books/selected-poems.jpg"
  },
  {
    "title": "The Bhagavad Gita",
    "author": "Eknath Easwaran",
    "categoryName": "Religion",
    "description": "Easwaran's best-selling translation of the Bhagavad Gita, the classic spiritual text of India. It features a reliable translation with clear chapter introductions.",
    "publisher": "Jaico Publishing House",
    "language": "English",
    "isbn": "9788184950915",
    "pageCount": 300,
    "price": 199,
    "originalPrice": 250,
    "stock": 30,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "religion",
      "gita",
      "spirituality"
    ],
    "coverImage": "/images/books/the-bhagavad-gita.jpg"
  },
  {
    "title": "Sapiens: A Brief History of Humankind",
    "author": "Yuval Noah Harari",
    "categoryName": "History",
    "description": "100,000 years ago, at least six human species inhabited the earth. Today there is just one. Us. Homo sapiens. How did our species succeed in the battle for dominance? Why did our foraging ancestors come together to create cities and kingdoms?",
    "publisher": "Harvill Secker",
    "language": "English",
    "isbn": "9780099590088",
    "pageCount": 512,
    "price": 499,
    "originalPrice": 599,
    "stock": 20,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "history",
      "sapiens",
      "harari",
      "anthropology"
    ],
    "coverImage": "/images/books/sapiens-a-brief-history-of-humankind.jpg"
  },
  {
    "title": "The Great Railway Bazaar",
    "author": "Paul Theroux",
    "categoryName": "Travel",
    "description": "Paul Theroux's account of his epic journey by train through Asia, including the Orient Express, the Khyber Pass Local, the Frontier Mail, and the Trans-Siberian Express.",
    "publisher": "Houghton Mifflin",
    "language": "English",
    "isbn": "9780141189123",
    "pageCount": 384,
    "price": 349,
    "originalPrice": 450,
    "stock": 10,
    "isFeatured": false,
    "isEbook": true,
    "ebookUrl": "https://res.cloudinary.com/demo/image/upload/v1570975200/sample.pdf",
    "tags": [
      "travel",
      "paul theroux",
      "railway"
    ],
    "coverImage": "/images/books/the-great-railway-bazaar.jpg"
  },
  {
    "title": "Gitanjali",
    "author": "Rabindranath Tagore",
    "categoryName": "Poetry",
    "description": "A collection of poems by the Nobel laureate Rabindranath Tagore. These song offerings are spiritual, deeply personal, and universally appealing.",
    "publisher": "Macmillan",
    "language": "English",
    "isbn": "9788171673322",
    "pageCount": 120,
    "price": 149,
    "originalPrice": 199,
    "stock": 25,
    "isFeatured": false,
    "isEbook": false,
    "tags": [
      "poetry",
      "tagore",
      "nobel",
      "india"
    ],
    "coverImage": "/images/books/gitanjali.jpg"
  },
  {
    "title": "The Innovators: How a Group of Hackers, Geniuses, and Geeks Created the Digital Revolution",
    "author": "Walter Isaacson",
    "categoryName": "Technology",
    "description": "The story of the people who created the computer and the internet. It is a guide to how collaboration and teamwork lead to innovation.",
    "publisher": "Simon & Schuster",
    "language": "English",
    "isbn": "9781476708690",
    "pageCount": 544,
    "price": 549,
    "originalPrice": 699,
    "stock": 15,
    "isFeatured": true,
    "isEbook": false,
    "tags": [
      "technology",
      "history",
      "innovation",
      "isaacson"
    ],
    "coverImage": "/images/books/the-innovators-how-a-group-of-hackers-geniuses-and-geeks-created-the-digital-revolution.jpg"
  }
];

const users = [
  {
    "name": "Admin User",
    "email": "admin@bookstore.com",
    "password": "admin123",
    "role": "admin",
    "phone": "9876543210",
    "address": {
      "street": "123 Admin Lane",
      "city": "Delhi",
      "state": "Delhi",
      "zipCode": "110001",
      "country": "India"
    }
  },
  {
    "name": "John Doe",
    "email": "user@bookstore.com",
    "password": "user123",
    "role": "user",
    "phone": "9876500000",
    "address": {
      "street": "456 User Street",
      "city": "Mumbai",
      "state": "Maharashtra",
      "zipCode": "400001",
      "country": "India"
    }
  }
];

const reviews = [
  {
    "bookTitle": "Clean Code: A Handbook of Agile Software Craftsmanship",
    "userEmail": "user@bookstore.com",
    "rating": 5,
    "comment": "An absolute masterpiece. This book completely changed the way I write code. A must-read for every computer science student and software engineer!"
  },
  {
    "bookTitle": "Steve Jobs",
    "userEmail": "user@bookstore.com",
    "rating": 4,
    "comment": "Extremely detailed and well-written biography. It shows Steve Jobs in his true light, with all his geniuses and flaws. Very inspiring!"
  },
  {
    "bookTitle": "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    "userEmail": "user@bookstore.com",
    "rating": 5,
    "comment": "James Clear did a fantastic job of breaking down habit formation into practical, actionable steps. Read it twice already!"
  },
  {
    "bookTitle": "Introduction to Algorithms",
    "userEmail": "user@bookstore.com",
    "rating": 5,
    "comment": "The bible of algorithms. While it can be mathematically heavy in some chapters, the explanations are crystal clear. Great reference book."
  },
  {
    "bookTitle": "Harry Potter and the Sorcerer's Stone",
    "userEmail": "user@bookstore.com",
    "rating": 5,
    "comment": "Absolutely magical. Brings back so many childhood memories. Rowling's world-building is top-notch!"
  },
  {
    "bookTitle": "The Silent Patient",
    "userEmail": "user@bookstore.com",
    "rating": 4,
    "comment": "Great psychological thriller. The twist at the end was completely unexpected. Kept me hooked till the very last page!"
  },
  {
    "bookTitle": "Dune",
    "userEmail": "user@bookstore.com",
    "rating": 4,
    "comment": "Epic world-building. It takes some time to get into the terminology, but once you do, it is incredibly rewarding. Masterpiece of sci-fi!"
  }
];

module.exports = {
  categories,
  books,
  users,
  reviews
};
